### ISSUE TITLE
What happend when I ran ./tools/dist_test.sh 

### ISSUE THREAD

**Issue by algoteam5** [zhengye1995/Zero-shot-Instance-Segmentation#20]
What does the following output indicate when I ran this command `./tools/dist_test.sh configs/zsi/65_15/test/gzsi/zero-shot-mask-rcnn-BARPN-bbox_mask_sync_bg_65_15_decoder_notanh_gzsi.py checkpoints/ZSI_65_15.pth 4 --show`?

```

gx = torch.addcmul(px, 1, pw, dx)  # gx = px + pw * dx
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>          ] 8112/10098, 12.9 task/s, elapsed: 654s, ETA
```

**Comment by zhengye1995** [comment]
Nothing happend except the inference process because  `--show` only works in single gpu model while you use 4 gpu to inference. See code [here](https://github.com/zhengye1995/Zero-shot-Instance-Segmentation/blob/45ee140205ce1f4acaaa6e72ddb526c962068378/tools/test.py#L29).

**Comment by algoteam5** [comment]
@zhengye1995 Why the inference took so long? normally it requires a few milliseconds to get inference from a trained model.

**Comment by zhengye1995** [comment]
@algoteam5 Because this process inferences all 10098 images in test label file,  which is determined by this [code](https://github.com/zhengye1995/Zero-shot-Instance-Segmentation/blob/6b25b318d7821b5f7a48f7d5e6dbd0bc63474e14/configs/zsi/65_15/test/zsi/zero-shot-mask-rcnn-BARPN-bbox_mask_sync_bg_65_15_decoder_notanh.py#L185) in config file.
