### ISSUE TITLE
version problem

### ISSUE THREAD

**Issue by JKZhan** [zhengye1995/Zero-shot-Instance-Segmentation#35]
Do you have experience using A100 to train your model ？ I use the install information you recommend but it can't run

**Comment by zhengye1995** [comment]
Sorry, I haven't experimented with A100 graphics cards, I think there should be tow problems for running my code in A100:
1. The torch version：this repo is based on torch1.1.0，which is a outdated version when using CUDA11+ in A100, so you need to build from the source code if you what to install torch1.1.0 in A100 with CUDA11+.
2. The CUDA version: the mmdetection(1.1.0) and mmcv(0.2.14) in this repo is based on CUDA10, I'm not sure if it will work fine in cuda11+ as well, since the A100 can only work with CUDA11+

**Comment by JKZhan** [comment]
what do you mean "build from the source code"?

**Comment by zhengye1995** [comment]
See   https://github.com/pytorch/pytorch#from-source

**Comment by JKZhan** [comment]
I got this issue  and   i had search for solution but still can't sovle it

subprocess.CalledProcessError: Command '['/home/jk/miniconda3/envs/zsi/bin/python', '-u', './tools/train.py', '--local_rank=0', 'configs/zsi/48_17/train/zero-shot-mask-rcnn-BARPN-bbox_mask_sync_bg_decoder.py', '--launcher', 'pytorch']' returned non-zero exit status 1.

**Comment by roiweer** [comment]
I also encountered this issue and can't solve it.

subprocess.CalledProcessError: Command '['/hy-nas/myenv/bin/python', '-u', './tools/train.py', '--local_rank=0', 'configs/zsi/train/zero-shot-mask-rcnn-BARPN-bbox_mask_sync_bg_decoder.py', '--launcher', 'pytorch']' returned non-zero exit status 1.

**Comment by roiweer** [comment]
> I made it ,thanks for your code!!!!

**Comment by lmhlll** [comment]
> 

Hi, How did you solve this problem?

**Comment by lmhlll** [comment]
@roiweer Hi, How did you solve this problem?
