### ISSUE TITLE
Question about detect any unseen class

### ISSUE THREAD

**Issue by shikiganye** [zhengye1995/Zero-shot-Instance-Segmentation#44]
Hello, the author. I want to know how to modify the code if I want to detect a new type of object (not belonging to 80 categories in COCO dataset)

**Comment by zhengye1995** [comment]
1. Add the word2vec of new category in word2vec file [word_w2v_withbg_48_17.txt](https://github.com/zhengye1995/Zero-shot-Instance-Segmentation/blob/main/data/coco/word_w2v_withbg_48_17.txt) or  [word_w2v_withbg_65_15.txt](https://github.com/zhengye1995/Zero-shot-Instance-Segmentation/blob/main/data/coco/word_w2v_withbg_65_15.txt). You can add it in the last column of the raw word2vec, and the results of the last class should be your target results.
2. Modify the code about the number of classes since my ugly handcraft code, you can refer this [issue](https://github.com/zhengye1995/Zero-shot-Instance-Segmentation/issues/40#issuecomment-1127154760)
